wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.3
    start_time: 1668044664.348458
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 1
      - 19
      - 23
      4: 3.8.3
      5: 0.13.4
      8:
      - 5
c:
  desc: null
  value: 10
data:
  desc: null
  value: sine
flow_model:
  desc: null
  value: coupling
z0_encoder:
  desc: null
  value: ode
